definitions:
  auth.Credentials:
    properties:
      login:
        type: string
      password:
        type: string
    required:
      - login
      - password
    type: object
  auth.Creds:
    properties:
      login:
        type: string
      name:
        type: string
      password:
        type: string
      role:
        type: string
    type: object
  auth.FullCredentials:
    properties:
      login:
        type: string
      name:
        type: string
      password:
        type: string
    required:
      - login
      - name
      - password
    type: object
  auth.Project:
    properties:
      cost:
        type: number
      dimension:
        type: string
      id:
        type: integer
      name:
        type: string
      type:
        type: string
    required:
      - cost
      - dimension
      - id
      - name
      - type
    type: object
  auth.ProjectDto:
    properties:
      cost:
        type: number
      dimension:
        type: string
      name:
        type: string
      type:
        type: string
    required:
      - cost
      - dimension
      - name
      - type
    type: object
  auth.User:
    properties:
      id:
        type: integer
      login:
        type: string
      name:
        type: string
      role:
        type: string
    type: object
  task.Task:
    properties:
      amount:
        type: integer
      client_name:
        type: string
      description:
        type: string
      id:
        type: integer
      project_id:
        type: integer
      user_id:
        type: integer
    required:
      - amount
      - client_name
      - description
      - id
      - project_id
      - user_id
    type: object
  task.TaskDto:
    properties:
      amount:
        type: integer
      client_name:
        type: string
      description:
        type: string
      project_id:
        type: integer
      user_id:
        type: integer
    required:
      - amount
      - client_name
      - description
      - project_id
      - user_id
    type: object
info:
  contact: {}
  title: Swagger Example API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
        - application/json
      parameters:
        - description: User creds to authenticate
          in: body
          name: credentials
          required: true
          schema:
            $ref: "#/definitions/auth.Credentials"
      responses:
        "204":
          description: User authenticated
        "400":
          description: Bad request
        "500":
          description: Internal server error
      summary: Login
      tags:
        - auth
  /auth/register:
    post:
      consumes:
        - application/json
      parameters:
        - description: User creds to register
          in: body
          name: credentials
          required: true
          schema:
            $ref: "#/definitions/auth.FullCredentials"
      responses:
        "204":
          description: User created
        "400":
          description: Bad request
        "500":
          description: Internal server error
      summary: Register
      tags:
        - auth
  /tasks:
    get:
      responses:
        "200":
          description: OK
          schema:
            projects:
              $ref: "#/definitions/task.Task"
            type: array
        "500":
          description: Internal server error
      summary: get all
      tags:
        - task
    patch:
      consumes:
        - application/json
      parameters:
        - description: Updating task
          in: body
          name: task
          required: true
          schema:
            $ref: "#/definitions/task.Task"
      responses:
        "204":
          description: Task updated
        "500":
          description: Internal server error
      summary: update task
      tags:
        - task
    post:
      consumes:
        - application/json
      parameters:
        - description: create task
          in: body
          name: task
          required: true
          schema:
            $ref: "#/definitions/task.TaskDto"
      responses:
        "201":
          description: Task created
        "400":
          description: Bad request
        "500":
          description: Internal server error
      summary: create task
      tags:
        - task
  /tasks/{id}:
    delete:
      consumes:
        - application/json
      parameters:
        - description: Task id
          in: body
          name: id
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: Task deleted
        "500":
          description: Internal server error
      summary: delete by id
      tags:
        - task
    get:
      consumes:
        - application/json
      parameters:
        - description: Task id
          in: body
          name: id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/task.Task"
        "400":
          description: Bad request
        "404":
          description: Task not found
      summary: get by id
      tags:
        - task
  /projects:
    get:
      responses:
        "200":
          description: OK
          schema:
            projects:
              $ref: "#/definitions/auth.Project"
            type: array
        "500":
          description: Internal server error
      summary: get all
      tags:
        - project
    patch:
      consumes:
        - application/json
      parameters:
        - description: Updating user
          in: body
          name: project
          required: true
          schema:
            $ref: "#/definitions/auth.Project"
      responses:
        "204":
          description: Project updated
        "500":
          description: Internal server error
      summary: update project
      tags:
        - project
    post:
      consumes:
        - application/json
      parameters:
        - description: create request
          in: body
          name: project
          required: true
          schema:
            $ref: "#/definitions/auth.ProjectDto"
      responses:
        "201":
          description: Project created
        "400":
          description: Bad request
        "500":
          description: Internal server error
      summary: create project
      tags:
        - project
  /projects/{id}:
    delete:
      consumes:
        - application/json
      parameters:
        - description: Project id
          in: body
          name: id
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: Project deleted
        "500":
          description: Internal server error
      summary: delete by id
      tags:
        - project
    get:
      consumes:
        - application/json
      parameters:
        - description: Project id
          in: body
          name: id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/auth.Project"
        "400":
          description: Bad request
        "404":
          description: Project not found
      summary: get by id
      tags:
        - project
  /users:
    get:
      responses:
        "200":
          description: OK
          schema:
            projects:
              $ref: "#/definitions/auth.User"
            type: array
        "500":
          description: Internal server error
      summary: get all
      tags:
        - user
    patch:
      consumes:
        - application/json
      parameters:
        - description: Updating user
          in: body
          name: user
          required: true
          schema:
            $ref: "#/definitions/auth.User"
      responses:
        "204":
          description: User updated
        "500":
          description: Internal server error
      summary: update user
      tags:
        - user
    post:
      consumes:
        - application/json
      parameters:
        - description: create request
          in: body
          name: user
          required: true
          schema:
            $ref: "#/definitions/auth.Creds"
      responses:
        "201":
          description: User created
        "400":
          description: Bad request
        "500":
          description: Internal server error
      summary: create user
      tags:
        - user
  /users/{id}:
    delete:
      consumes:
        - application/json
      parameters:
        - description: User id
          in: body
          name: id
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: User deleted
        "500":
          description: Internal server error
      summary: delete by id
      tags:
        - user
    get:
      consumes:
        - application/json
      parameters:
        - description: User id
          in: body
          name: id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/auth.User"
        "400":
          description: Bad request
        "404":
          description: User not found
      summary: get by id
      tags:
        - user
swagger: "2.0"
